### ISSUE TITLE
Docker container sensitive to network environment used to build vs run

### ISSUE THREAD

**Issue by robharper** [unchartedsoftware/salt#17]
While on my home network the container won't run due to the need to connect to the external internet to download gradle + dependencies. I need to add ```--dns 8.8.8.8``` to the run commandline.

Taking a look at `/etc/resolv.conf` I see it references search and nameservers specific to the work network I originally built the container on. 

Do I have something misconfigured, are containers not expected to run on networks different than those on which they are built, or should we add `8.8.8.8` to `resolv.conf`?

**Comment by Ghnuberath** [comment]
Likely fixed by SHA: 51fa8140dd69f324540811295ff1ea7a3cf0252e
